version: '3.9'

services:
  nestapp:
    container_name: nestapp
    image: dice/nestapp:1.0.0
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=210440
      - PG_DB=doc
      - PG_PORT=5432
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:16
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=210440
      - POSTGRES_DB=doc
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
